$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: job-salary-prediction
experiment_name: basic-nn-architecture
description: A pipeline job to split-preprocess-train-test 

settings:
    default_compute: azureml:cluster-cpu

jobs:
  split:
    type: command
    component: azureml:component_pipeline_cli_split@latest
    inputs:
      raw_data:
        type: uri_file
        path: azureml:raw_data@latest
        mode: download
    outputs:
      train_data:
        type: uri_file
        mode: rw_mount
        path: azureml://subscriptions/a8c5d49d-e0aa-4576-97cc-fa6b18ce0f6a/resourcegroups/rg001/workspaces/WS001/datastores/workspaceblobstore/paths/LocalUpload/73375df799e563845861e11ed586aa7d/train.csv
      validation_data:
        type: uri_file
        mode: rw_mount
        path: azureml://subscriptions/a8c5d49d-e0aa-4576-97cc-fa6b18ce0f6a/resourcegroups/rg001/workspaces/WS001/datastores/workspaceblobstore/paths/LocalUpload/73375df799e563845861e11ed586aa7d/validation.csv
      test_data:
        type: uri_file
        mode: rw_mount
        path: azureml://subscriptions/a8c5d49d-e0aa-4576-97cc-fa6b18ce0f6a/resourcegroups/rg001/workspaces/WS001/datastores/workspaceblobstore/paths/LocalUpload/73375df799e563845861e11ed586aa7d/test.csv

  preprocess:
    type: command
    component: azureml:component_pipeline_cli_preprocess@latest
    inputs:
      train_data: ${{parent.jobs.split.outputs.train_data}}
      validation_data: ${{parent.jobs.split.outputs.validation_data}}
      test_data: ${{parent.jobs.split.outputs.test_data}}
    outputs:
      train_batches: 
        type: uri_folder
        path: azureml://subscriptions/a8c5d49d-e0aa-4576-97cc-fa6b18ce0f6a/resourcegroups/rg001/workspaces/WS001/datastores/workspaceblobstore/paths/LocalUpload/73375df799e563845861e11ed586aa7d/train
        mode: rw_mount
      validation_batches:
        type: uri_folder
        path: azureml://subscriptions/a8c5d49d-e0aa-4576-97cc-fa6b18ce0f6a/resourcegroups/rg001/workspaces/WS001/datastores/workspaceblobstore/paths/LocalUpload/73375df799e563845861e11ed586aa7d/validation
        mode: rw_mount
      test_batches:
        type: uri_folder
        path: azureml://subscriptions/a8c5d49d-e0aa-4576-97cc-fa6b18ce0f6a/resourcegroups/rg001/workspaces/WS001/datastores/workspaceblobstore/paths/LocalUpload/73375df799e563845861e11ed586aa7d/test
        mode: rw_mount
      features_dim:
        type: uri_file
        path: azureml://subscriptions/a8c5d49d-e0aa-4576-97cc-fa6b18ce0f6a/resourcegroups/rg001/workspaces/WS001/datastores/workspaceblobstore/paths/LocalUpload/73375df799e563845861e11ed586aa7d/features_dim.csv
        mode: rw_mount

  train:
    type: command
    component: azureml:component_pipeline_cli_train@latest
    inputs:
      epochs: 5
      train_batches: ${{parent.jobs.preprocess.outputs.train_batches}}
      validation_batches: ${{parent.jobs.preprocess.outputs.validation_batches}}
      features_dim: ${{parent.jobs.preprocess.outputs.features_dim}}
    outputs:
      model_dir:
        type: mlflow_model
        mode: upload

  test:
    type: command
    component: azureml:component_pipeline_cli_test@latest
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
      test_batches: ${{parent.jobs.preprocess.outputs.test_batches}}