$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: job-salary-prediction
description: A pipeline job to split-preprocess-train-test 


inputs:
  data_dir:
    path: azureml:Train-Data@latest
    type: uri_folder

outputs:
  model_dir:
    type: mlflow_model
  pipeline_job_split_data:
    mode: upload


settings:
    default_compute: azureml:cluster-cpu


jobs:
  split:
    type: command
    component: azureml:component_pipeline_cli_split@latest
    inputs:
      data_dir: ${{parent.inputs.data_dir}}
    # outputs:
    #   processed_data_dir: ${{parent.jobs.processed_data_dir.outputs}}

  # preprocess:
  #   type: command
  #   component: azureml:component_pipeline_cli_preprocess@latest
  #   inputs:
  #     data_dir: ${{parent.jobs.split.outputs.train_dir}}
  #   outputs:
  #     data_dir: ${{job.outputs.data_dir}}
      
  # train:
  #   type: command
  #   component: azureml:component_pipeline_cli_train@latest
  #   inputs:
  #     data_dir: ${{parent.inputs.data_dir}}
  #   outputs:
  #     model_dir: ${{parent.outputs.model_dir}}

  # test:
  #   type: command
  #   component: azureml:component_pipeline_cli_test@latest
  #   inputs:
  #     data_dir: ${{parent.inputs.data_dir}}
  #     model_dir: ${{parent.jobs.train.outputs.model_dir}}